name: Deploy backend to EC2 with Docker

on: 
  push:
    branches:
      - cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build --platform linux/amd64 -t ashank2001/mcquizbackend .
      - name: Publish Image to docker hub
        run: docker push ashank2001/mcquizbackend:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull ashank2001/mcquizbackend:latest 
      - name: Delete old container
        run: docker rm -f mcquizbackend-container || true
      - name: Run Docker Container
        run: |
          docker run -d -p 3001:3001 --name mcquizbackend-container \
            -e PORT=${{ secrets.PORT }} \
            -e HOST=${{ secrets.HOST }} \
            -e FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
            -e MONGODB_URI=${{ secrets.MONGODB_URI }} \
            -e CLIENT_ID=${{ secrets.CLIENT_ID }} \
            -e CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} \
            -e PAYHERE_MERCHANT_ID=${{ secrets.PAYHERE_MERCHANT_ID }} \
            -e PAYHERE_MERCHANT_SECRET=${{ secrets.PAYHERE_MERCHANT_SECRET }} \
            -e ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }} \
            -e ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} \
            -e EMAIL_USER=${{ secrets.EMAIL_USER }} \
            -e EMAIL_PASS=${{ secrets.EMAIL_PASS }} \
            ashank2001/mcquizbackend:latest 